import { useState, useEffect, useRef } from "react";
const R="#E31E24",R2="#B91C22",D="'DM Sans',sans-serif",C="'Cormorant Garamond',serif";
// App URLs — all on the same domain under different paths
const APP_URLS={
  auto:"/auction",
  logistics:"/logistics",
  admin:"/admin",
};
function Logo({size="md"}){const s={sm:{fs:14,px:10,py:5},md:{fs:19,px:14,py:6},lg:{fs:28,px:20,py:8},hero:{fs:56,px:40,py:14}}[size]||{fs:19,px:14,py:6};return<div style={{display:"inline-flex",alignItems:"center",justifyContent:"center",padding:`${s.py}px ${s.px}px`,background:R}}><span style={{fontSize:s.fs,fontWeight:900,color:"#fff",letterSpacing:"0.06em",fontFamily:D,lineHeight:1}}>SAYARAH</span></div>;}
const companies=[
{id:"capital",name:"SAYARAH CAPITAL",short:"Capital",type:"Investment Firm",appUrl:"https://sayarahcapital.com/",appLabel:"LAUNCH CAPITAL",tagline:"We build, elevate, and co-invest in businesses, sharing in the upside.",hero:"Strategic capital for growth-stage businesses across automotive, logistics, and fintech.",description:"Sayarah Capital is a Boston-based investment firm deploying growth capital into exceptional SMBs. We partner deeply with founders, bringing operational expertise in automotive commerce, global logistics, and technology platforms.",features:[{title:"Direct Investment",desc:"Meaningful positions aligned with founders for long-term value creation."},{title:"Operational Support",desc:"Access to Sayarah's logistics network, sourcing, and technology."},{title:"Growth Partnership",desc:"Active board involvement, strategic planning, global network."},{title:"Flexible Structures",desc:"Equity, revenue-based, and hybrid structures for each business."}],stats:[{l:"FOUNDED",v:"2025"},{l:"HQ",v:"Boston, MA"},{l:"FOCUS",v:"Growth SMBs"},{l:"TICKET",v:"$250K–$5M"}],metrics:[{label:"Portfolio Companies",value:"4"},{label:"Capital Deployed",value:"$5M+"},{label:"Revenue Growth",value:"3.2x"},{label:"Industries",value:"3"}],icon:<svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>},
{id:"auto",name:"SAYARAH AUTO",short:"Auto",type:"Vehicle Sourcing & Export",appUrl:"https://sayarahauto.com/",appLabel:"LAUNCH PLATFORM",tagline:"Buy & ship cars from US auto auctions to the Middle East, Central Asia, and Africa.",hero:"55,000+ vehicles weekly. 14+ countries. Auction-to-doorstep.",description:"Sayarah Auto connects international buyers with the largest US auto auction inventory. Licensed access to Copart, IAAI, Manheim — full purchasing, title processing, compliance, and international shipping.",features:[{title:"Auction Access",desc:"Licensed bidding on Copart, IAAI, Manheim with 55,000+ weekly vehicles."},{title:"Title & Compliance",desc:"Complete title processing, export docs, customs forms."},{title:"Shipping Calculator",desc:"Transparent quotes — base rate, port fees, insurance."},{title:"End-to-End Tracking",desc:"Auction win to port delivery — full pipeline visibility."}],stats:[{l:"VEHICLES/WK",v:"55,000+"},{l:"DESTINATIONS",v:"14+"},{l:"PORTS",v:"6"},{l:"SERVICE",v:"Full"}],metrics:[{label:"Vehicles Shipped",value:"2,400+"},{label:"Avg. Savings",value:"22%"},{label:"Repeat Buyers",value:"78%"},{label:"Avg. Transit",value:"28 Days"}],icon:<svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5"><path d="M7 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"/><path d="M17 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"/><path d="M5 17h-2v-6l2-5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0h-6m-6-6h15m-6 0v-5"/></svg>},
{id:"logistics",name:"SAYARAH LOGISTICS",short:"Logistics",type:"Shipping & Logistics Platform",appUrl:APP_URLS.logistics,appLabel:"OPEN LOGISTICS",tagline:"Industry-grade shipment tracking, container management, invoicing, and demurrage.",hero:"US port to global doorstep — full visibility at every stage.",description:"The operational backbone — managing international vehicle shipping. Towing, container loading, ocean freight tracking, demurrage calculation, and professional invoice generation with customer portals.",features:[{title:"11-Stage Pipeline",desc:"Purchased → Title → Warehouse → Loading → Shipped → Transit → Customs → Delivered."},{title:"Demurrage Engine",desc:"Real-time by carrier (MSC, Maersk, CMA CGM) with storage, detention, NOC."},{title:"Auto-Invoice",desc:"Select container, auto-populate vehicles/fees, Sayarah-format invoices."},{title:"Customer Portal",desc:"Track shipments, view invoices, real-time status — no admin needed."}],stats:[{l:"PIPELINE",v:"11 Stages"},{l:"CARRIERS",v:"MSC·Maersk"},{l:"INVOICING",v:"Auto"},{l:"DEMURRAGE",v:"Real-Time"}],metrics:[{label:"Containers/Mo",value:"45+"},{label:"Customers",value:"120+"},{label:"Accuracy",value:"99.8%"},{label:"Clearance",value:"3 Days"}],icon:<svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5"><rect x="1" y="3" width="15" height="13" rx="2"/><path d="M16 8h4l3 3v5h-7V8z"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>},
];
export default function SayarahGroup(){
const[page,setPage]=useState("home");const[activeCo,setActiveCo]=useState(null);const[scrollY,setScrollY]=useState(0);const[visible,setVisible]=useState(new Set());const refs=useRef({});
useEffect(()=>{const h=()=>setScrollY(window.scrollY);window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h);},[]);
useEffect(()=>{const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)setVisible(p=>new Set([...p,e.target.dataset.id]));});},{threshold:.12});Object.values(refs.current).forEach(el=>el&&obs.observe(el));return()=>obs.disconnect();},[page]);
const reg=id=>el=>{if(el){el.dataset.id=id;refs.current[id]=el;}};const vis=id=>visible.has(id);
const go=(pg,co=null)=>{setPage(pg);setActiveCo(co);setVisible(new Set());refs.current={};window.scrollTo(0,0);};const navDk=page!=="home"||scrollY>60;
return(
<div style={{fontFamily:C,background:"#FDFAFA",color:"#111",overflowX:"hidden"}}>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;500;600;700&family=DM+Sans:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>
<style>{`*{margin:0;padding:0;box-sizing:border-box}@keyframes fadeUp{from{opacity:0;transform:translateY(40px)}to{opacity:1;transform:translateY(0)}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}@keyframes float{0%,100%{transform:translateY(0) rotate(45deg)}50%{transform:translateY(-12px) rotate(45deg)}}@keyframes pulse{0%,100%{opacity:.35}50%{opacity:.85}}@keyframes shimmer{0%{background-position:-200% 0}100%{background-position:200% 0}}.fu{opacity:0;transform:translateY(40px);transition:all .8s cubic-bezier(.16,1,.3,1)}.fu.v{opacity:1;transform:translateY(0)}.pc{transition:transform .4s cubic-bezier(.16,1,.3,1),box-shadow .4s}.pc:hover{transform:translateY(-6px);box-shadow:0 24px 48px rgba(227,30,36,.14)}.cb{transition:all .3s ease}.cb:hover{background:${R}!important;color:#fff!important;transform:scale(1.03);box-shadow:0 8px 24px rgba(227,30,36,.2)}.nl{transition:color .25s,transform .2s}.nl:hover{color:${R}!important;transform:translateX(2px)}.glow{height:2px;background:linear-gradient(90deg,transparent,${R},transparent);animation:shimmer 3s ease infinite;background-size:200% 100%}.rdot{width:6px;height:6px;border-radius:50%;background:${R};animation:pulse 2s ease infinite}::selection{background:rgba(227,30,36,.18)}html{scroll-behavior:smooth}@media(max-width:768px){nav{padding:0 16px!important}nav>div{height:56px!important}.footer-grid{grid-template-columns:1fr!important;gap:24px!important}.detail-grid{grid-template-columns:1fr!important;gap:24px!important}.hero-stats{gap:20px!important;flex-wrap:wrap}.hero-btns{flex-wrap:wrap}}@media(max-width:480px){.hero-stats>div{min-width:60px}}`}</style>
{/* NAV */}
<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,background:navDk?"rgba(255,255,255,.97)":"transparent",backdropFilter:navDk?"blur(12px)":"none",borderBottom:navDk?`1px solid rgba(227,30,36,.06)`:"none",transition:"all .4s",padding:"0 48px"}}>
<div style={{maxWidth:1200,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"space-between",height:72}}>
<div onClick={()=>go("home")} style={{cursor:"pointer"}}><Logo size="sm"/></div>
<div style={{display:"flex",gap:28,alignItems:"center"}}>{[{l:"Home",p:"home"},{l:"Portfolio",p:"portfolio"}].map(n=><span key={n.l} onClick={()=>go(n.p)} className="nl" style={{fontSize:12,fontWeight:700,letterSpacing:"0.08em",textTransform:"uppercase",color:navDk?(page===n.p?R:"#374151"):"rgba(255,255,255,.7)",cursor:"pointer",fontFamily:D}}>{n.l}</span>)}<div style={{height:16,width:1,background:navDk?"#E5E7EB":"rgba(255,255,255,.15)"}}/><a href={APP_URLS.auto} target="_blank" rel="noopener noreferrer" style={{fontSize:10,fontWeight:800,letterSpacing:"0.1em",textTransform:"uppercase",color:navDk?"#111":"rgba(255,255,255,.8)",cursor:"pointer",fontFamily:D,textDecoration:"none",padding:"6px 14px",background:navDk?"#111":"rgba(255,255,255,.12)",transition:"all .3s"}} onMouseEnter={e=>{e.currentTarget.style.background=R;e.currentTarget.style.color="#fff";}} onMouseLeave={e=>{e.currentTarget.style.background=navDk?"#111":"rgba(255,255,255,.12)";e.currentTarget.style.color=navDk?"#fff":"rgba(255,255,255,.8)";}}>AUTO TRADE HUB</a><a href={APP_URLS.admin} target="_blank" rel="noopener noreferrer" style={{fontSize:10,fontWeight:800,letterSpacing:"0.1em",textTransform:"uppercase",color:navDk?R:"rgba(255,255,255,.8)",cursor:"pointer",fontFamily:D,textDecoration:"none",padding:"6px 14px",border:`1.5px solid ${navDk?R:"rgba(255,255,255,.3)"}`,transition:"all .3s"}} onMouseEnter={e=>{e.currentTarget.style.background=R;e.currentTarget.style.color="#fff";e.currentTarget.style.borderColor=R;}} onMouseLeave={e=>{e.currentTarget.style.background="transparent";e.currentTarget.style.color=navDk?R:"rgba(255,255,255,.8)";e.currentTarget.style.borderColor=navDk?R:"rgba(255,255,255,.3)";}}>ADMIN</a></div>
</div></nav>
{page==="home"&&<HomePage go={go} reg={reg} vis={vis}/>}
{page==="portfolio"&&<PortfolioPage go={go} reg={reg} vis={vis}/>}
{page==="detail"&&activeCo&&<DetailPage co={activeCo} go={go} reg={reg} vis={vis}/>}
{/* WHITE FOOTER */}
<footer style={{background:"#fff",position:"relative",overflow:"hidden"}}>
<div className="glow" style={{height:3}}/>
<div style={{position:"absolute",top:40,right:-20,width:100,height:100,border:`1px solid rgba(227,30,36,.05)`,transform:"rotate(45deg)"}}/>
<div style={{position:"absolute",bottom:20,left:-15,width:60,height:60,border:`1px solid rgba(227,30,36,.04)`,transform:"rotate(45deg)"}}/>
<div style={{maxWidth:1200,margin:"0 auto",padding:"52px 24px 0"}}>
<div className="footer-grid" style={{display:"grid",gridTemplateColumns:"2.5fr 1fr 1fr 1fr",gap:48,marginBottom:44}}>
<div><div style={{marginBottom:18}}><Logo size="md"/></div><p style={{fontSize:14,lineHeight:1.8,fontFamily:D,maxWidth:300,color:"#6B7280"}}>A vertically integrated group serving the global automotive trade ecosystem.</p><div style={{fontSize:12,fontFamily:D,marginTop:16,color:"#9CA3AF",lineHeight:1.8}}>275 Grove Street, Suite 2-400<br/>Newton, MA 02466</div><a href="mailto:support@sayarah.io" style={{fontSize:12,fontFamily:D,color:R,fontWeight:700,textDecoration:"none",marginTop:10,display:"inline-block"}}>support@sayarah.io</a></div>
{[{t:"Companies",ls:companies.map(c=>({l:c.short,a:()=>go("detail",c)}))},{t:"Platforms",ls:[{l:"Auto Trade Hub",href:APP_URLS.auto},{l:"Logistics",href:APP_URLS.logistics},{l:"Admin Panel",href:APP_URLS.admin},{l:"Portfolio",a:()=>go("portfolio")}]},{t:"Connect",ls:[{l:"Contact Us"},{l:"Careers"},{l:"Press"},{l:"Privacy"}]}].map(col=>
<div key={col.t}><div style={{fontSize:11,letterSpacing:"0.12em",color:R,fontFamily:D,fontWeight:800,marginBottom:16,textTransform:"uppercase",display:"flex",alignItems:"center",gap:8}}><div className="rdot"/>{col.t}</div>{col.ls.map(lnk=>lnk.href?<a key={lnk.l} href={lnk.href} target="_blank" rel="noopener noreferrer" className="nl" style={{fontSize:13,fontFamily:D,marginBottom:11,cursor:"pointer",color:"#6B7280",fontWeight:500,textDecoration:"none",display:"block"}}>{lnk.l}</a>:<div key={lnk.l} onClick={lnk.a} className="nl" style={{fontSize:13,fontFamily:D,marginBottom:11,cursor:"pointer",color:"#6B7280",fontWeight:500}}>{lnk.l}</div>)}</div>
)}</div>
<div className="glow"/>
<div style={{padding:"20px 0 28px",display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:11,fontFamily:D,color:"#9CA3AF"}}><span>© 2025 Sayarah Inc. All rights reserved. Atlantic Car Connect is a company of Sayarah Inc.</span><div style={{display:"flex",gap:16,alignItems:"center"}}><span>Boston, MA</span><div style={{display:"flex",gap:3}}>{[1,2,3].map(i=><div key={i} style={{width:4,height:4,background:R,opacity:.2+i*.2,borderRadius:1}}/>)}</div></div></div>
</div></footer>
</div>);}
function HomePage({go,reg,vis}){return<>
<section style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",position:"relative",overflow:"hidden",background:`linear-gradient(135deg,${R} 0%,#A8161B 30%,#5C0C10 65%,#1A0507 100%)`}}>
<div style={{position:"absolute",top:"8%",left:"6%",width:120,height:120,border:"1px solid rgba(255,255,255,.06)",transform:"rotate(45deg)",animation:"float 8s ease-in-out infinite"}}/>
<div style={{position:"absolute",top:"20%",right:"10%",width:80,height:80,border:"1px solid rgba(255,255,255,.04)",transform:"rotate(45deg)",animation:"float 6s ease-in-out infinite 1s"}}/>
<div style={{position:"absolute",bottom:"15%",left:"12%",width:60,height:60,background:"rgba(227,30,36,.08)",transform:"rotate(45deg)",animation:"float 7s ease-in-out infinite .5s"}}/>
<div style={{position:"absolute",bottom:"25%",right:"8%",width:200,height:200,border:"1px solid rgba(255,255,255,.03)",transform:"rotate(45deg)"}}/>
<div style={{position:"relative",zIndex:1,textAlign:"center",maxWidth:800,padding:"0 24px"}}>
<div style={{animation:"fadeIn 1.2s ease",marginBottom:24,display:"inline-flex",alignItems:"center",gap:16}}><div style={{height:1,width:60,background:"rgba(255,255,255,.25)"}}/><div style={{width:10,height:10,background:"rgba(255,255,255,.2)",transform:"rotate(45deg)"}}/><div style={{height:1,width:60,background:"rgba(255,255,255,.25)"}}/></div>
<div style={{animation:"fadeUp 1s ease .2s both",marginBottom:12}}><Logo size="hero"/></div>
<div style={{fontSize:"clamp(14px,2vw,18px)",letterSpacing:"0.35em",color:"rgba(255,255,255,.4)",fontFamily:D,fontWeight:600,animation:"fadeUp 1s ease .4s both"}}>GROUP OF COMPANIES</div>
<p style={{fontSize:"clamp(16px,1.8vw,20px)",color:"rgba(255,255,255,.5)",lineHeight:1.7,maxWidth:560,margin:"36px auto 0",fontWeight:300,animation:"fadeUp 1s ease .6s both"}}>We build, elevate, and invest in businesses across automotive commerce, global logistics, and financial technology.</p>
<div className="hero-btns" style={{display:"flex",justifyContent:"center",gap:20,marginTop:44,animation:"fadeUp 1s ease .8s both"}}>
<button onClick={()=>go("portfolio")} style={{padding:"16px 36px",background:"#fff",color:R,fontSize:12,fontWeight:800,letterSpacing:"0.12em",border:"none",cursor:"pointer",fontFamily:D}}>EXPLORE PORTFOLIO →</button>
<button onClick={()=>go("detail",companies[0])} style={{padding:"16px 36px",border:"1px solid rgba(255,255,255,.25)",background:"transparent",color:"rgba(255,255,255,.8)",fontSize:12,fontWeight:700,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D}}>INVESTOR PORTAL</button>
</div>
<div className="hero-stats" style={{display:"flex",justifyContent:"center",gap:52,marginTop:64,animation:"fadeUp 1s ease 1s both"}}>{[["4","Companies"],["14+","Countries"],["$5M+","Deployed"],["2025","Founded"]].map(([v,l])=><div key={l} style={{textAlign:"center"}}><div style={{fontSize:26,fontWeight:300,color:"#fff"}}>{v}</div><div style={{fontSize:10,letterSpacing:"0.12em",color:"rgba(255,255,255,.3)",fontFamily:D,fontWeight:600,marginTop:4,textTransform:"uppercase"}}>{l}</div></div>)}</div>
</div>
<div style={{position:"absolute",bottom:32,left:"50%",transform:"translateX(-50%)",textAlign:"center",animation:"fadeIn 1.5s ease 1.5s both"}}><div style={{fontSize:10,letterSpacing:"0.15em",color:"rgba(255,255,255,.3)",fontFamily:D,fontWeight:600,marginBottom:8}}>SCROLL</div><div style={{width:1,height:36,background:"linear-gradient(to bottom,rgba(255,255,255,.3),transparent)",margin:"0 auto"}}/></div>
</section>
<div style={{maxWidth:1200,margin:"0 auto",padding:"0 24px"}}><div className="glow"/></div>
<section style={{padding:"90px 24px",maxWidth:1200,margin:"0 auto"}}>
<div ref={reg("hc-t")} className={`fu ${vis("hc-t")?"v":""}`} style={{textAlign:"center",marginBottom:56}}>
<div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:16}}><div style={{height:1,width:40,background:R}}/><div className="rdot"/><div style={{height:1,width:40,background:R}}/></div>
<h2 style={{fontSize:"clamp(36px,5vw,54px)",fontWeight:300,lineHeight:1.1}}>Four Pillars of <span style={{fontStyle:"italic",color:R}}>Sayarah</span></h2>
</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:20}}>
{companies.map((co,i)=><div key={co.id} ref={reg(`hc-${co.id}`)} className={`fu pc ${vis(`hc-${co.id}`)?"v":""}`} style={{transitionDelay:`${i*.12}s`,background:"#fff",border:"1px solid #EDE0E0",cursor:"pointer",position:"relative",overflow:"hidden"}} onClick={()=>go("detail",co)}>
<div style={{height:3,background:`linear-gradient(90deg,${R},${R2})`}}/><div style={{position:"absolute",top:0,right:0,width:0,height:0,borderStyle:"solid",borderWidth:"0 44px 44px 0",borderColor:`transparent ${R} transparent transparent`,opacity:.85}}/>
<div style={{padding:"30px 26px"}}><div style={{marginBottom:18,opacity:.8}}>{co.icon}</div><h3 style={{fontSize:16,fontWeight:700,letterSpacing:"0.05em",fontFamily:D,marginBottom:4}}>{co.name}</h3><div style={{fontSize:10,color:R,fontWeight:700,fontFamily:D,marginBottom:12,letterSpacing:"0.04em"}}>{co.type}</div><p style={{fontSize:13,color:"#6B7280",lineHeight:1.6,fontFamily:D,marginBottom:18,minHeight:40}}>{co.tagline}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><div className="cb" style={{display:"inline-flex",alignItems:"center",gap:8,padding:"10px 18px",background:R,color:"#fff",fontSize:10,fontWeight:800,letterSpacing:"0.1em",fontFamily:D,border:"none",cursor:"pointer"}}>LEARN MORE →</div>{co.appUrl&&<a href={co.appUrl} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"10px 18px",background:"#111",color:"#fff",fontSize:10,fontWeight:800,letterSpacing:"0.1em",fontFamily:D,border:"none",cursor:"pointer",textDecoration:"none",transition:"all .3s"}} onMouseEnter={e=>{e.currentTarget.style.background=R;e.currentTarget.style.boxShadow="0 8px 24px rgba(227,30,36,.3)";}} onMouseLeave={e=>{e.currentTarget.style.background="#111";e.currentTarget.style.boxShadow="none";}}>▶ {co.appLabel||"LAUNCH APP"}</a>}</div></div>
</div>)}
</div>
<div style={{textAlign:"center",marginTop:44}}><button onClick={()=>go("portfolio")} className="cb" style={{padding:"16px 44px",background:R,color:"#fff",border:"none",fontSize:12,fontWeight:800,letterSpacing:"0.12em",cursor:"pointer",fontFamily:D}}>VIEW FULL PORTFOLIO →</button></div>
</section>
{/* ─── Quick Access Platforms ─── */}
<section style={{background:"#111",padding:"72px 24px",position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",top:0,left:0,right:0}}><div className="glow"/></div>
<div style={{position:"absolute",top:"10%",right:"5%",width:120,height:120,border:"1px solid rgba(227,30,36,.08)",transform:"rotate(45deg)"}}/>
<div ref={reg("apps-h")} className={`fu ${vis("apps-h")?"v":""}`} style={{textAlign:"center",marginBottom:48}}>
<div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:16}}><div style={{height:1,width:40,background:R}}/><div className="rdot"/><div style={{height:1,width:40,background:R}}/></div>
<h2 style={{fontSize:"clamp(28px,4vw,42px)",fontWeight:300,lineHeight:1.15,color:"#fff"}}>Our <span style={{fontStyle:"italic",color:R}}>Platforms</span></h2>
<p style={{fontSize:14,color:"rgba(255,255,255,.4)",fontFamily:D,maxWidth:500,margin:"14px auto 0",lineHeight:1.7}}>Access your tools — auction management, logistics tracking, and admin control.</p>
</div>
<div style={{maxWidth:900,margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16}}>
{[
  {name:"Auto Trade Hub",desc:"Car flipping accounting, deal grading, inventory management",url:APP_URLS.auto,icon:<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>,gradient:"linear-gradient(135deg,#1A0507,#3D0A0C)"},
  {name:"Logistics",desc:"Shipment tracking, containers, invoicing, customer portal",url:APP_URLS.logistics,icon:<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M2 20h20M5 20V10l7-6 7 6v10"/><path d="M4 20l-2-6h20l-2 6"/><line x1="12" y1="4" x2="12" y2="2"/><path d="M9 20v-4h6v4"/></svg>,gradient:"linear-gradient(135deg,#0A0D1A,#0C1A3D)"},
  {name:"Admin Panel",desc:"Unified control center — manage users, permissions, both apps",url:APP_URLS.admin,icon:<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke={R} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0110 0v4"/></svg>,gradient:"linear-gradient(135deg,#0D1A0A,#1A3D0C)"},
].map((app,i)=><div key={app.name} ref={reg(`app-${i}`)} className={`fu ${vis(`app-${i}`)?"v":""}`} style={{transitionDelay:`${i*.12}s`}}>
  <a href={app.url} target="_blank" rel="noopener noreferrer" style={{display:"block",textDecoration:"none",background:app.gradient,border:"1px solid rgba(227,30,36,.15)",padding:"32px 26px",position:"relative",overflow:"hidden",transition:"all .4s cubic-bezier(.16,1,.3,1)",cursor:"pointer"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-6px)";e.currentTarget.style.boxShadow="0 24px 48px rgba(227,30,36,.2)";e.currentTarget.style.borderColor="rgba(227,30,36,.4)";}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="none";e.currentTarget.style.borderColor="rgba(227,30,36,.15)";}}>
    <div style={{position:"absolute",top:0,right:0,width:0,height:0,borderStyle:"solid",borderWidth:"0 40px 40px 0",borderColor:`transparent ${R} transparent transparent`,opacity:.6}}/>
    <div style={{fontSize:32,marginBottom:14}}>{app.icon}</div>
    <div style={{fontSize:16,fontWeight:800,color:"#fff",fontFamily:D,letterSpacing:"0.04em",marginBottom:6}}>{app.name}</div>
    <div style={{fontSize:12,color:"rgba(255,255,255,.45)",fontFamily:D,lineHeight:1.6,marginBottom:20}}>{app.desc}</div>
    <div style={{display:"inline-flex",alignItems:"center",gap:8,padding:"10px 22px",background:R,color:"#fff",fontSize:10,fontWeight:800,letterSpacing:"0.12em",fontFamily:D}}>▶ LAUNCH APP</div>
  </a>
</div>)}
</div>
</section>
{/* ─── CTA ─── */}
<section style={{background:"#fff",padding:"72px 24px 56px",position:"relative",overflow:"hidden"}}>
<div className="glow" style={{position:"absolute",top:0,left:0,right:0}}/><div style={{position:"absolute",top:20,right:60,width:90,height:90,border:`1px solid rgba(227,30,36,.05)`,transform:"rotate(45deg)",animation:"float 8s ease-in-out infinite"}}/>
<div ref={reg("cta-h")} className={`fu ${vis("cta-h")?"v":""}`} style={{maxWidth:640,margin:"0 auto",textAlign:"center"}}>
<div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:20}}><div style={{height:1,width:40,background:R}}/><div className="rdot"/><div style={{height:1,width:40,background:R}}/></div>
<h2 style={{fontSize:"clamp(28px,4vw,42px)",fontWeight:300,lineHeight:1.15,marginBottom:16}}>Ready to work with <span style={{fontStyle:"italic",color:R}}>Sayarah?</span></h2>
<p style={{fontSize:15,color:"#6B7280",fontFamily:D,marginBottom:32,lineHeight:1.7}}>Whether you're looking to invest, source vehicles, ship cargo, or manage your fleet — we have the platform for you.</p>
<div style={{display:"flex",justifyContent:"center",gap:14}}><button onClick={()=>go("portfolio")} className="cb" style={{padding:"16px 36px",background:R,color:"#fff",border:"none",fontSize:12,fontWeight:800,letterSpacing:"0.12em",cursor:"pointer",fontFamily:D}}>EXPLORE PORTFOLIO →</button><button className="cb" style={{padding:"16px 36px",background:"transparent",color:R,border:`2px solid ${R}`,fontSize:12,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D}}>CONTACT US</button></div>
</div></section>
</>;}
function PortfolioPage({go,reg,vis}){return<>
<section style={{paddingTop:72,background:`linear-gradient(135deg,#2A0A0C 0%,#140507 50%,#0D0D0D 100%)`,minHeight:400,display:"flex",alignItems:"center",justifyContent:"center",position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",top:"10%",right:"8%",width:140,height:140,border:"1px solid rgba(255,255,255,.03)",transform:"rotate(45deg)"}}/>
<div style={{textAlign:"center",position:"relative",zIndex:1,padding:"56px 24px"}}><div style={{animation:"fadeIn .8s ease",marginBottom:14}}><Logo size="md"/></div><h1 style={{fontSize:"clamp(40px,6vw,68px)",fontWeight:300,color:"#fff",lineHeight:1,animation:"fadeUp .8s ease .2s both"}}>Our Companies</h1><p style={{fontSize:16,color:"rgba(255,255,255,.4)",fontFamily:D,maxWidth:480,margin:"18px auto 0",animation:"fadeUp .8s ease .4s both",lineHeight:1.7}}>Four vertically integrated businesses powering global automotive trade.</p></div>
</section>
{companies.map((co,idx)=>{const even=idx%2===0;const bg=even?"#FDFAFA":"#fff";return(
<section key={co.id} style={{background:bg,padding:"72px 24px",position:"relative"}}>
{even&&<div style={{position:"absolute",top:0,right:0,width:180,height:180,background:"rgba(227,30,36,.02)",transform:"rotate(45deg)",transformOrigin:"top right"}}/>}
<div style={{maxWidth:1100,margin:"0 auto"}}>
<div ref={reg(`p-${co.id}`)} className={`fu ${vis(`p-${co.id}`)?"v":""}`} style={{marginBottom:40}}>
<div style={{display:"flex",alignItems:"center",gap:18,marginBottom:16}}><span style={{fontSize:56,fontWeight:300,color:"rgba(227,30,36,.08)",fontFamily:C,lineHeight:1}}>{String(idx+1).padStart(2,"0")}</span><div><div style={{fontSize:11,letterSpacing:"0.15em",color:R,fontFamily:D,fontWeight:700,marginBottom:3}}>{co.type.toUpperCase()}</div><h2 style={{fontSize:"clamp(26px,4vw,40px)",fontWeight:400,lineHeight:1.1}}>{co.name}</h2></div></div>
<p style={{fontSize:17,fontWeight:300,color:"#374151",lineHeight:1.6,maxWidth:560}}>{co.hero}</p></div>
<div ref={reg(`pd-${co.id}`)} className={`fu detail-grid ${vis(`pd-${co.id}`)?"v":""}`} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:44,marginBottom:40}}>
<div><p style={{fontSize:14,color:"#6B7280",lineHeight:1.8,fontFamily:D,marginBottom:20}}>{co.description}</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>go("detail",co)} className="cb" style={{padding:"14px 28px",background:R,color:"#fff",border:"none",fontSize:11,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D}}>LEARN MORE →</button>{co.appUrl&&<a href={co.appUrl} target="_blank" rel="noopener noreferrer" style={{padding:"14px 28px",background:"#111",color:"#fff",border:"none",fontSize:11,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D,textDecoration:"none",display:"inline-flex",alignItems:"center",gap:8,transition:"all .3s"}} onMouseEnter={e=>{e.currentTarget.style.background=R;e.currentTarget.style.boxShadow="0 8px 24px rgba(227,30,36,.3)";}} onMouseLeave={e=>{e.currentTarget.style.background="#111";e.currentTarget.style.boxShadow="none";}}>▶ {co.appLabel||"LAUNCH APP"}</a>}</div></div>
<div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:18}}>{co.metrics.map(m=><div key={m.label} style={{background:bg==="#fff"?"#FDFAFA":"#fff",border:"1px solid #EDE0E0",padding:"18px 14px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,width:"100%",height:2,background:`linear-gradient(90deg,${R},transparent)`}}/><div style={{fontSize:24,fontWeight:300,color:R,fontFamily:C}}>{m.value}</div><div style={{fontSize:9,letterSpacing:"0.08em",color:"#9CA3AF",fontFamily:D,fontWeight:700,marginTop:3,textTransform:"uppercase"}}>{m.label}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{co.stats.map(s=><div key={s.l} style={{borderTop:`2px solid rgba(227,30,36,.06)`,paddingTop:6}}><div style={{fontSize:9,letterSpacing:"0.1em",color:"#9CA3AF",fontFamily:D,fontWeight:700}}>{s.l}</div><div style={{fontSize:13,fontWeight:800,fontFamily:D,marginTop:2}}>{s.v}</div></div>)}</div></div>
</div>
<div ref={reg(`pf-${co.id}`)} className={`fu ${vis(`pf-${co.id}`)?"v":""}`} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}>{co.features.map((f,fi)=><div key={fi} style={{padding:"22px 18px",background:bg==="#fff"?"#FDFAFA":"#fff",border:"1px solid #EDE0E0",borderLeft:`3px solid ${R}`}}><div style={{fontSize:14,fontWeight:700,fontFamily:D,marginBottom:5}}>{f.title}</div><div style={{fontSize:12,color:"#6B7280",lineHeight:1.7,fontFamily:D}}>{f.desc}</div></div>)}</div>
</div>
{idx<companies.length-1&&<div style={{maxWidth:1100,margin:"48px auto 0"}}><div className="glow"/></div>}
</section>);})}
<section style={{background:"#fff",padding:"64px 24px 48px",position:"relative",overflow:"hidden"}}>
<div className="glow" style={{position:"absolute",top:0,left:0,right:0}}/>
<div style={{maxWidth:600,margin:"0 auto",textAlign:"center"}}><div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:18}}><div style={{height:1,width:40,background:R}}/><div className="rdot"/><div style={{height:1,width:40,background:R}}/></div><h2 style={{fontSize:34,fontWeight:300,marginBottom:14}}>Interested in <span style={{fontStyle:"italic",color:R}}>partnering?</span></h2><p style={{fontSize:14,color:"#6B7280",fontFamily:D,marginBottom:28}}>Let's explore what's possible together.</p><div style={{display:"flex",justifyContent:"center",gap:12}}><button onClick={()=>go("home")} className="cb" style={{padding:"14px 36px",background:R,color:"#fff",border:"none",fontSize:12,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D}}>BACK TO HOME →</button><button className="cb" style={{padding:"14px 36px",background:"transparent",color:R,border:`2px solid ${R}`,fontSize:12,fontWeight:800,letterSpacing:"0.08em",cursor:"pointer",fontFamily:D}}>CONTACT US</button></div></div>
</section></>;}
function DetailPage({co,go,reg,vis}){return<>
<section style={{paddingTop:72,background:`linear-gradient(135deg,${R} 0%,#A8161B 40%,#3D0A0C 100%)`,minHeight:460,display:"flex",alignItems:"center",position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",top:"15%",right:"6%",width:180,height:180,border:"1px solid rgba(255,255,255,.04)",transform:"rotate(45deg)"}}/>
<div style={{position:"absolute",bottom:"10%",left:"4%",width:90,height:90,background:"rgba(227,30,36,.08)",transform:"rotate(45deg)"}}/>
<div style={{maxWidth:1100,margin:"0 auto",padding:"56px 24px",position:"relative",zIndex:1,width:"100%"}}>
<div style={{animation:"fadeUp .8s ease both"}}><div style={{marginBottom:14}}><Logo size="sm"/></div><div onClick={()=>go("portfolio")} style={{display:"inline-flex",alignItems:"center",gap:8,color:"rgba(255,255,255,.5)",fontFamily:D,fontSize:12,fontWeight:600,cursor:"pointer",marginBottom:20,letterSpacing:"0.06em"}}>← BACK TO PORTFOLIO</div><div style={{fontSize:11,letterSpacing:"0.15em",color:"rgba(255,255,255,.3)",fontFamily:D,fontWeight:700,marginBottom:6}}>{co.type.toUpperCase()}</div><h1 style={{fontSize:"clamp(38px,6vw,60px)",fontWeight:300,color:"#fff",lineHeight:1.05,marginBottom:14}}>{co.name}</h1><p style={{fontSize:17,color:"rgba(255,255,255,.5)",fontFamily:D,maxWidth:500,lineHeight:1.6}}>{co.hero}</p></div>
<div style={{display:"flex",gap:36,marginTop:36,animation:"fadeUp .8s ease .3s both",alignItems:"center",flexWrap:"wrap"}}>{co.stats.map(s=><div key={s.l}><div style={{fontSize:20,fontWeight:300,color:"#fff"}}>{s.v}</div><div style={{fontSize:9,letterSpacing:"0.12em",color:"rgba(255,255,255,.3)",fontFamily:D,fontWeight:700,marginTop:2}}>{s.l}</div></div>)}</div>
{co.appUrl&&<div style={{marginTop:36,animation:"fadeUp .8s ease .5s both"}}><a href={co.appUrl} target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:10,padding:"18px 40px",background:"#fff",color:R,fontSize:13,fontWeight:900,letterSpacing:"0.12em",fontFamily:D,textDecoration:"none",transition:"all .3s",boxShadow:"0 8px 32px rgba(0,0,0,.3)"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.boxShadow="0 12px 40px rgba(0,0,0,.4)";}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="0 8px 32px rgba(0,0,0,.3)";}}>▶ {co.appLabel||"LAUNCH APP"}</a></div>}
</div></section>
<section style={{padding:"64px 24px",maxWidth:1100,margin:"0 auto"}}>
<div ref={reg("cd-a")} className={`fu detail-grid ${vis("cd-a")?"v":""}`} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:48}}>
<div><div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:14}}><div style={{height:1,width:40,background:R}}/><span style={{fontSize:11,letterSpacing:"0.2em",color:R,fontFamily:D,fontWeight:700}}>OVERVIEW</span></div><h2 style={{fontSize:34,fontWeight:300,lineHeight:1.15,marginBottom:18}}>About <span style={{fontStyle:"italic",color:R}}>{co.short}</span></h2><p style={{fontSize:14,color:"#6B7280",lineHeight:1.8,fontFamily:D}}>{co.description}</p></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{co.metrics.map(m=><div key={m.label} style={{background:"#FDFAFA",border:"1px solid #EDE0E0",padding:"22px 18px",position:"relative"}}><div style={{position:"absolute",top:0,left:0,width:"100%",height:2,background:`linear-gradient(90deg,${R},transparent)`}}/><div style={{fontSize:30,fontWeight:300,color:R,fontFamily:C}}>{m.value}</div><div style={{fontSize:9,letterSpacing:"0.08em",color:"#9CA3AF",fontFamily:D,fontWeight:700,marginTop:5,textTransform:"uppercase"}}>{m.label}</div></div>)}</div>
</div></section>
<section style={{padding:"0 24px 64px",maxWidth:1100,margin:"0 auto"}}>
<div ref={reg("cd-f")} className={`fu ${vis("cd-f")?"v":""}`}><div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:18}}><div style={{height:1,width:40,background:R}}/><span style={{fontSize:11,letterSpacing:"0.2em",color:R,fontFamily:D,fontWeight:700}}>CAPABILITIES</span></div><h2 style={{fontSize:30,fontWeight:300,lineHeight:1.15,marginBottom:32}}>What <span style={{fontStyle:"italic",color:R}}>{co.short}</span> offers</h2>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:16}}>{co.features.map((f,i)=><div key={i} ref={reg(`cdf-${i}`)} className={`fu ${vis(`cdf-${i}`)?"v":""}`} style={{transitionDelay:`${i*.1}s`,padding:"26px 22px",background:"#fff",border:"1px solid #EDE0E0",borderLeft:`3px solid ${R}`}}><div style={{fontSize:28,fontWeight:300,color:"rgba(227,30,36,.1)",fontFamily:C,marginBottom:6}}>{String(i+1).padStart(2,"0")}</div><div style={{fontSize:14,fontWeight:700,fontFamily:D,marginBottom:6}}>{f.title}</div><div style={{fontSize:12,color:"#6B7280",lineHeight:1.7,fontFamily:D}}>{f.desc}</div></div>)}</div>
</div></section>
<section style={{background:"#1A0507",padding:"56px 24px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:32}}><div style={{fontSize:11,letterSpacing:"0.2em",color:R,fontFamily:D,fontWeight:700,marginBottom:6}}>EXPLORE MORE</div><h2 style={{fontSize:26,fontWeight:300,color:"#fff"}}>Other Companies</h2></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14}}>{companies.filter(c=>c.id!==co.id).map(c=><div key={c.id} onClick={()=>go("detail",c)} className="pc" style={{background:"rgba(227,30,36,.06)",border:"1px solid rgba(227,30,36,.1)",padding:"26px 22px",cursor:"pointer"}}><div style={{fontSize:14,fontWeight:700,color:"#fff",fontFamily:D,marginBottom:3}}>{c.name}</div><div style={{fontSize:10,color:R,fontFamily:D,fontWeight:700,letterSpacing:"0.06em",marginBottom:8}}>{c.type}</div><div style={{fontSize:12,color:"rgba(255,255,255,.4)",fontFamily:D,lineHeight:1.6,marginBottom:14}}>{c.tagline}</div><span style={{fontSize:10,fontWeight:800,color:"rgba(255,255,255,.5)",fontFamily:D,letterSpacing:"0.1em"}}>VIEW →</span></div>)}</div></div></section>
<section style={{background:"#fff",padding:"56px 24px 44px",position:"relative",overflow:"hidden"}}><div className="glow" style={{position:"absolute",top:0,left:0,right:0}}/>
<div style={{maxWidth:560,margin:"0 auto",textAlign:"center"}}><div style={{display:"inline-flex",alignItems:"center",gap:12,marginBottom:18}}><div style={{height:1,width:40,background:R}}/><div className="rdot"/><div style={{height:1,width:40,background:R}}/></div><h2 style={{fontSize:30,fontWeight:300,marginBottom:12}}>Get Started with <span style={{fontStyle:"italic",color:R}}>{co.short}</span></h2><p style={{fontSize:13,color:"#6B7280",fontFamily:D,marginBottom:24}}>{co.tagline}</p><div style={{display:"flex",justifyContent:"center",gap:12,flexWrap:"wrap"}}>{co.appUrl?<a href={co.appUrl} target="_blank" rel="noopener noreferrer" className="cb" style={{padding:"14px 32px",background:R,color:"#fff",border:"none",fontSize:12,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D,textDecoration:"none",display:"inline-flex",alignItems:"center",gap:8}}>▶ {co.appLabel||"LAUNCH APP"}</a>:<button className="cb" style={{padding:"14px 32px",background:R,color:"#fff",border:"none",fontSize:12,fontWeight:800,letterSpacing:"0.1em",cursor:"pointer",fontFamily:D}}>GET STARTED →</button>}<button onClick={()=>go("portfolio")} className="cb" style={{padding:"14px 32px",background:"transparent",color:R,border:`2px solid ${R}`,fontSize:12,fontWeight:700,letterSpacing:"0.08em",cursor:"pointer",fontFamily:D}}>ALL COMPANIES</button></div></div></section>
</>;}
